"""Generated by `make seed`. Do not edit by hand.

Public keys only, imported by both the engine and the standalone verifier.
Editing a key here makes every receipt from that issuer fail.
"""

PUBLIC_KEYS: dict[str, str] = {
    "ramify:demo:issuer:Concordia_Labs_AU": "600a62c40c0bfaa7411679228ea11e9ac5fa81d8e2dfbd1a4ed0c90d6967acb6",
    "ramify:demo:issuer:GMP_AU_demo": "e54a76537c2112765a1f0cc07194c6389a25baf69c6881dd05961fed6e33239e",
    "ramify:demo:issuer:Regulator_AU_demo": "da329d78ccc50b0332365b26764865b506814b8572bb76a224b7095b5ce821c3",
    "ramify:demo:signer:receipt": "ec17a9af4f1a88b02701aefa80eec2925225b27af471d6b1adae99d4df8d2932",
}
