"""Generated by `make seed`. Do not edit by hand.

Public keys only, imported by both the server and the standalone verifier.
Editing a key here makes every receipt from that issuer fail.
"""

PUBLIC_KEYS: dict[str, str] = {
    "ramify:demo:issuer:Concordia_Labs_AU": "5c82707e4bbcd10843eea71504f725409aef395197d5334c5c314934b9bc2e0d",
    "ramify:demo:issuer:GMP_AU_demo": "8dcd13627dacfa06368fb3c54395a26c5a804a6a9b6ff1a77eb4d6ffdb12b04d",
    "ramify:demo:issuer:Regulator_AU_demo": "278055489f6dc3c5c0f93929619f5650cc3d177ecf80f077200710e13ab2df4a",
    "ramify:demo:signer:receipt": "ec17a9af4f1a88b02701aefa80eec2925225b27af471d6b1adae99d4df8d2932",
}
