"""Ed25519 key lifecycle — amendment v0.4.1 item 1.

Two kinds of private key, handled differently. Issuer keys sign the fixtures
during the seed step and never ship. The RAMIFY signer key must be available at
runtime, because the demo signs new receipts live, so it goes into the local
data store on first run.

Public keys are generated into `embedded_pubkeys.py` and imported by both the
engine and the standalone verifier. The verifier holds public keys only.
"""

import json
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

from ramify.storage import StoreCorrupt, read_json, write_json_atomic

ISSUER_REFS = (
    "ramify:demo:issuer:Concordia_Labs_AU",
    "ramify:demo:issuer:Regulator_AU_demo",
    "ramify:demo:issuer:GMP_AU_demo",
)
RAMIFY_SIGNER = "ramify:demo:signer:receipt"


class SignerKeyError(RuntimeError):
    """Existing local signing identity is missing/corrupt and must not be rotated silently."""


_PACKAGE_ROOT = Path(__file__).resolve().parent
_PROJECT_ROOT = _PACKAGE_ROOT.parents[2]
SEED_PRIVATE_DIR = _PROJECT_ROOT / "seed_private"
EMBEDDED_PUBKEYS_PATH = _PACKAGE_ROOT / "embedded_pubkeys.py"


def local_data_store() -> Path:
    """Mutable per-machine state, created on first run. Spec section 3.3.

    `RAMIFY_DATA_DIR` redirects it; the test suite points it at a temp
    directory so the suite does not fill the demo's review queue with fixtures.
    """
    override = os.environ.get("RAMIFY_DATA_DIR")
    if override:
        return Path(override)
    if sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA", Path.home()))
        return base / "ramify-demo" / "v11.0"
    return Path.home() / ".ramify-demo" / "v11.0"


def _to_raw_private(key: Ed25519PrivateKey) -> bytes:
    return key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )


def _to_raw_public(key: Ed25519PublicKey) -> bytes:
    return key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )


def generate_keypairs() -> dict[str, dict[str, str]]:
    """Generate the three issuer keypairs and the RAMIFY signer keypair."""
    keypairs = {}
    for ref in (*ISSUER_REFS, RAMIFY_SIGNER):
        private = Ed25519PrivateKey.generate()
        keypairs[ref] = {
            "private_hex": _to_raw_private(private).hex(),
            "public_hex": _to_raw_public(private.public_key()).hex(),
        }
    return keypairs


def write_seed_material(keypairs: dict[str, dict[str, str]]) -> None:
    """Write the private keys, then generate the embedded public-key module.

    The signer key is written here too so `make seed-reset` can restore a wiped
    store without a rekey, which would invalidate every receipt already issued.
    """
    SEED_PRIVATE_DIR.mkdir(parents=True, exist_ok=True)
    (SEED_PRIVATE_DIR / "keys.json").write_text(
        json.dumps(keypairs, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _write_embedded_pubkeys(keypairs)
    # During a seed/rekey operation the generated signer may be installed into
    # the current machine's local data store, but its private material is never
    # copied into the distributable project tree.
    install_signer_key()


def _write_embedded_pubkeys(keypairs: dict[str, dict[str, str]]) -> None:
    lines = [
        '"""Generated by `make seed`. Do not edit by hand.',
        "",
        "Public keys only, imported by both the server and the standalone verifier.",
        "Editing a key here makes every receipt from that issuer fail.",
        '"""',
        "",
        "PUBLIC_KEYS: dict[str, str] = {",
    ]
    for ref in sorted(keypairs):
        lines.append(f'    "{ref}": "{keypairs[ref]["public_hex"]}",')
    lines.append("}")
    # newline="\n": on Windows, write_text otherwise produces a CRLF file.
    EMBEDDED_PUBKEYS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def _sync_runtime_signer_public(private: Ed25519PrivateKey) -> Path:
    """Ensure the machine-local public half matches the installed private key.

    Older RAMIFY builds persisted only ``signer_key.json``.  A newer build may
    therefore find a valid legacy private key but no matching runtime public-key
    file (or a stale one).  Receipt verification must follow the installed
    private key, not an unrelated public key embedded in the downloaded build.
    """
    store = local_data_store()
    store.mkdir(parents=True, exist_ok=True)
    public_target = store / "signer_public_key.json"
    expected = _to_raw_public(private.public_key()).hex()

    current = None
    if public_target.exists():
        try:
            payload = read_json(public_target, dict)
            value = payload.get(RAMIFY_SIGNER)
            if isinstance(value, str):
                current = value.lower()
        except StoreCorrupt:
            current = None

    if current != expected:
        write_json_atomic(public_target, {RAMIFY_SIGNER: expected})
    return public_target


SIGNER_FILES = ("signer_key.json", "signer_public_key.json", "signer_history.json")


def _current_signer_public_hex() -> str | None:
    """The public half of whatever signer this store holds now, if any."""
    store = local_data_store()
    try:
        raw = read_json(store / "signer_key.json", dict).get(RAMIFY_SIGNER)
        if isinstance(raw, str):
            return _to_raw_public(Ed25519PrivateKey.from_private_bytes(bytes.fromhex(raw)).public_key()).hex()
    except (StoreCorrupt, AttributeError, TypeError, ValueError):
        pass
    try:
        value = read_json(store / "signer_public_key.json", dict).get(RAMIFY_SIGNER)
        if isinstance(value, str) and len(value) == 64:
            return value.lower()
    except (StoreCorrupt, AttributeError):
        pass
    return None


def retired_signer_keys() -> list[str]:
    """Public keys of signers this store used before its current one.

    Kept so a receipt exported before a key was lost or rotated can still be
    checked against the key that signed it. Public material only.
    """
    try:
        value = read_json(local_data_store() / "signer_history.json", list)
    except StoreCorrupt:
        return []
    if not isinstance(value, list):
        return []
    return [k.lower() for k in value if isinstance(k, str) and len(k) == 64]


def _retire_signer_being_replaced(new_public_hex: str) -> None:
    current = _current_signer_public_hex()
    if current is None or current == new_public_hex:
        return
    history = retired_signer_keys()
    if current not in history:
        history.append(current)
        write_json_atomic(local_data_store() / "signer_history.json", history)


def _write_runtime_signer(private: Ed25519PrivateKey) -> Path:
    """Persist one machine-local synthetic signer and its public half.

    If another signer was here before, its public key is kept in
    signer_history.json rather than lost with it.
    """
    store = local_data_store()
    store.mkdir(parents=True, exist_ok=True)
    _retire_signer_being_replaced(_to_raw_public(private.public_key()).hex())
    private_target = store / "signer_key.json"
    write_json_atomic(private_target, {RAMIFY_SIGNER: _to_raw_private(private).hex()})
    _sync_runtime_signer_public(private)
    try:
        private_target.chmod(0o600)
    except OSError:
        pass
    return private_target


def install_signer_key() -> Path:
    """Install a synthetic runtime signer without shipping private key material.

    Seed/rekey can install the just-generated signer from the temporary
    seed_private directory. A normal downloaded demo has no seed_private tree,
    so first run generates a fresh machine-local signer instead.
    """
    seed_file = SEED_PRIVATE_DIR / "keys.json"
    if seed_file.exists():
        keypairs = json.loads(seed_file.read_text(encoding="utf-8"))
        raw = bytes.fromhex(keypairs[RAMIFY_SIGNER]["private_hex"])
        private = Ed25519PrivateKey.from_private_bytes(raw)
    else:
        private = Ed25519PrivateKey.generate()
    return _write_runtime_signer(private)


def load_signer_private_key() -> Ed25519PrivateKey:
    """Load the machine-local signer and repair its public half when required.

    This includes migration from pre-hardening builds that stored only the
    private signer.  Keeping the existing valid private key preserves the local
    signer identity and avoids invalidating receipts merely because the
    application package was upgraded.
    """
    target = local_data_store() / "signer_key.json"
    if not target.exists():
        # First run and key loss look identical at this line, and they are not.
        # A ledger beside a missing key means receipts were signed by an
        # identity that is now gone: generating a replacement would leave every
        # historical receipt failing signature verification, which on a
        # tamper-evidence product reads as tampering rather than as the file
        # loss it actually is. Only a genuinely fresh store may mint a signer.
        ledger = local_data_store() / "receipts.jsonl"
        if ledger.exists() and ledger.stat().st_size > 0:
            raise SignerKeyError(
                "The RAMIFY signing key is missing but this machine already has a "
                "receipt ledger. Those receipts were signed by the missing key and "
                "cannot be verified without it. Restore the key from backup, or "
                "explicitly reset/rekey the demo signer, which starts a new ledger."
            )
        install_signer_key()
    try:
        payload = read_json(target, dict)
        raw = payload[RAMIFY_SIGNER]
        private = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(raw))
        _sync_runtime_signer_public(private)
        return private
    except (StoreCorrupt, KeyError, TypeError, ValueError) as exc:
        # Never silently rotate an existing signing identity. Historical
        # receipts would immediately stop verifying and the operator would not
        # know why. Missing state is created on first run above; corrupt state
        # is an explicit recovery event.
        raise SignerKeyError(
            "The existing RAMIFY signing key is corrupt or unreadable. "
            "Back up the local ledger, then explicitly reset/rekey the demo signer."
        ) from exc


def load_issuer_private_key(issuer_ref: str) -> Ed25519PrivateKey:
    """Seed-step only. Issuer private keys are not available at runtime."""
    seed_file = SEED_PRIVATE_DIR / "keys.json"
    if not seed_file.exists():
        raise FileNotFoundError("no seed material; run `make seed` first")
    keypairs = json.loads(seed_file.read_text(encoding="utf-8"))
    return Ed25519PrivateKey.from_private_bytes(
        bytes.fromhex(keypairs[issuer_ref]["private_hex"])
    )


def public_keys() -> dict[str, str]:
    try:
        from ramify.crypto.embedded_pubkeys import PUBLIC_KEYS
    except ImportError as exc:  # pragma: no cover - exercised by a fresh clone
        raise RuntimeError(
            "embedded public keys are missing; run `make seed`"
        ) from exc
    merged = dict(PUBLIC_KEYS)

    # Migration/repair path: if a legacy machine-local private signer exists,
    # derive its public half directly. This prevents an upgraded demo from
    # verifying a receipt against the unrelated signer key embedded in the new
    # package. It also repairs a missing/stale signer_public_key.json file.
    private_target = local_data_store() / "signer_key.json"
    if private_target.exists():
        try:
            payload = read_json(private_target, dict)
            raw = payload.get(RAMIFY_SIGNER)
            if isinstance(raw, str):
                private = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(raw))
                value = _to_raw_public(private.public_key()).hex()
                merged[RAMIFY_SIGNER] = value
                _sync_runtime_signer_public(private)
                return merged
        except (StoreCorrupt, TypeError, ValueError):
            # Corrupt private state is handled by load_signer_private_key() when
            # signing is next attempted. Do not trust a stale public companion.
            pass

    runtime_public = local_data_store() / "signer_public_key.json"
    if runtime_public.exists():
        try:
            payload = read_json(runtime_public, dict)
            value = payload.get(RAMIFY_SIGNER)
            if isinstance(value, str) and len(value) == 64:
                merged[RAMIFY_SIGNER] = value
        except StoreCorrupt:
            pass
    return merged


def fingerprint(public_hex: str) -> str:
    """A comparable name for a public key: SHA-256 over its raw 32 bytes."""
    import hashlib

    return "sha256:" + hashlib.sha256(bytes.fromhex(public_hex)).hexdigest()


def signer_fingerprint() -> str | None:
    """Fingerprint of the key this machine verifies receipts against.

    Each installation mints its own signer, and a proof pack ships the public
    half alongside the receipts it signed. A receipt verifying therefore proves
    only that it matches the key it came with. Showing the fingerprint lets a
    person compare it with the value RAMIFY publishes, which is the check that
    actually establishes who signed.
    """
    raw = public_keys().get(RAMIFY_SIGNER)
    return fingerprint(raw) if raw else None


def load_public_key(ref: str) -> Ed25519PublicKey | None:
    raw = public_keys().get(ref)
    if raw is None:
        return None
    return Ed25519PublicKey.from_public_bytes(bytes.fromhex(raw))
