"""Ed25519 key lifecycle — amendment v0.4.1 item 1.

Two kinds of private key, handled differently. Issuer keys sign the fixtures
during the seed step and never ship. The RAMIFY signer key must be available at
runtime, because the demo signs new receipts live, so it goes into the local
data store on first run.

Public keys are generated into `embedded_pubkeys.py` and imported by both the
engine and the standalone verifier. The verifier holds public keys only.
"""

import json
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

from ramify.storage import StoreCorrupt, read_json, write_json_atomic

ISSUER_REFS = (
    "ramify:demo:issuer:Concordia_Labs_AU",
    "ramify:demo:issuer:Regulator_AU_demo",
    "ramify:demo:issuer:GMP_AU_demo",
)
RAMIFY_SIGNER = "ramify:demo:signer:receipt"


class SignerKeyError(RuntimeError):
    """Existing local signing identity is missing/corrupt and must not be rotated silently."""


_PACKAGE_ROOT = Path(__file__).resolve().parent
_PROJECT_ROOT = _PACKAGE_ROOT.parents[2]
SEED_PRIVATE_DIR = _PROJECT_ROOT / "seed_private"
EMBEDDED_PUBKEYS_PATH = _PACKAGE_ROOT / "embedded_pubkeys.py"


def local_data_store() -> Path:
    """Mutable per-machine state, created on first run. Spec section 3.3.

    `RAMIFY_DATA_DIR` redirects it; the test suite points it at a temp
    directory so the suite does not fill the demo's review queue with fixtures.
    """
    override = os.environ.get("RAMIFY_DATA_DIR")
    if override:
        return Path(override)
    if sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA", Path.home()))
        return base / "ramify-demo" / "v11.0"
    return Path.home() / ".ramify-demo" / "v11.0"


def _to_raw_private(key: Ed25519PrivateKey) -> bytes:
    return key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )


def _to_raw_public(key: Ed25519PublicKey) -> bytes:
    return key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )


def generate_keypairs() -> dict[str, dict[str, str]]:
    """Generate the three issuer keypairs and the RAMIFY signer keypair."""
    keypairs = {}
    for ref in (*ISSUER_REFS, RAMIFY_SIGNER):
        private = Ed25519PrivateKey.generate()
        keypairs[ref] = {
            "private_hex": _to_raw_private(private).hex(),
            "public_hex": _to_raw_public(private.public_key()).hex(),
        }
    return keypairs


def write_seed_material(keypairs: dict[str, dict[str, str]]) -> None:
    """Write the private keys, then generate the embedded public-key module.

    The signer key is written here too so `make seed-reset` can restore a wiped
    store without a rekey, which would invalidate every receipt already issued.
    """
    SEED_PRIVATE_DIR.mkdir(parents=True, exist_ok=True)
    (SEED_PRIVATE_DIR / "keys.json").write_text(
        json.dumps(keypairs, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _write_embedded_pubkeys(keypairs)
    # During a seed/rekey operation the generated signer may be installed into
    # the current machine's local data store, but its private material is never
    # copied into the distributable project tree.
    install_signer_key(force=True)


def _write_embedded_pubkeys(keypairs: dict[str, dict[str, str]]) -> None:
    lines = [
        '"""Generated by `make seed`. Do not edit by hand.',
        "",
        "Public keys only, imported by both the server and the standalone verifier.",
        "Editing a key here makes every receipt from that issuer fail.",
        '"""',
        "",
        "PUBLIC_KEYS: dict[str, str] = {",
    ]
    for ref in sorted(keypairs):
        lines.append(f'    "{ref}": "{keypairs[ref]["public_hex"]}",')
    lines.append("}")
    EMBEDDED_PUBKEYS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _sync_runtime_signer_public(private: Ed25519PrivateKey) -> Path:
    """Ensure the machine-local public half matches the installed private key.

    Older RAMIFY builds persisted only ``signer_key.json``.  A newer build may
    therefore find a valid legacy private key but no matching runtime public-key
    file (or a stale one).  Receipt verification must follow the installed
    private key, not an unrelated public key embedded in the downloaded build.
    """
    store = local_data_store()
    store.mkdir(parents=True, exist_ok=True)
    public_target = store / "signer_public_key.json"
    expected = _to_raw_public(private.public_key()).hex()

    current = None
    if public_target.exists():
        try:
            payload = read_json(public_target, dict)
            value = payload.get(RAMIFY_SIGNER)
            if isinstance(value, str):
                current = value.lower()
        except StoreCorrupt:
            current = None

    if current != expected:
        write_json_atomic(public_target, {RAMIFY_SIGNER: expected})
    return public_target


def _write_runtime_signer(private: Ed25519PrivateKey) -> Path:
    """Persist one machine-local synthetic signer and its public half."""
    store = local_data_store()
    store.mkdir(parents=True, exist_ok=True)
    private_target = store / "signer_key.json"
    write_json_atomic(private_target, {RAMIFY_SIGNER: _to_raw_private(private).hex()})
    _sync_runtime_signer_public(private)
    try:
        private_target.chmod(0o600)
    except OSError:
        pass
    return private_target


def _store_has_signing_history(store: Path) -> bool:
    """Return True when local state already depends on the signer identity."""
    for name in ("receipts.jsonl", "actions.jsonl"):
        path = store / name
        if path.exists() and path.stat().st_size > 0:
            return True

    cart_path = store / "cart.json"
    if cart_path.exists():
        try:
            payload = read_json(cart_path, dict)
            if any(payload.get(key) for key in ("lines", "orders", "requisitions")):
                return True
        except StoreCorrupt:
            # Corrupt historical state must not trigger silent identity rotation.
            return True
    return False


def install_signer_key(*, force: bool = False) -> Path:
    """Install a synthetic runtime signer without silent identity rotation.

    Normal first run may create a signer.  If receipt/transaction history is
    already present and the private signer is missing, installation fails closed
    unless an explicit seed/rekey operation passes ``force=True``.
    """
    store = local_data_store()
    target = store / "signer_key.json"
    if target.exists() and not force:
        # Keep the installed identity rather than overwriting it merely because
        # seed material happens to be available.
        payload = read_json(target, dict)
        raw = payload[RAMIFY_SIGNER]
        private = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(raw))
        _sync_runtime_signer_public(private)
        return target

    # Calling install_signer_key() is an explicit recovery/seed action. Silent
    # rotation is prevented in load_signer_private_key(), the normal runtime path.
    seed_file = SEED_PRIVATE_DIR / "keys.json"
    if seed_file.exists():
        keypairs = json.loads(seed_file.read_text(encoding="utf-8"))
        raw = bytes.fromhex(keypairs[RAMIFY_SIGNER]["private_hex"])
        private = Ed25519PrivateKey.from_private_bytes(raw)
    else:
        private = Ed25519PrivateKey.generate()
    return _write_runtime_signer(private)


def load_signer_private_key() -> Ed25519PrivateKey:
    """Load the machine-local signer and repair its public half when required.

    This includes migration from pre-hardening builds that stored only the
    private signer.  Keeping the existing valid private key preserves the local
    signer identity and avoids invalidating receipts merely because the
    application package was upgraded.
    """
    store = local_data_store()
    target = store / "signer_key.json"
    if not target.exists():
        if _store_has_signing_history(store):
            raise SignerKeyError(
                "RAMIFY signing material is missing while existing receipt/transaction history remains. "
                "The signer will not be rotated silently; use an explicit recovery or rekey procedure."
            )
        install_signer_key()
    try:
        payload = read_json(target, dict)
        raw = payload[RAMIFY_SIGNER]
        private = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(raw))
        _sync_runtime_signer_public(private)
        return private
    except (StoreCorrupt, KeyError, TypeError, ValueError) as exc:
        # Never silently rotate an existing signing identity. Historical
        # receipts would immediately stop verifying and the operator would not
        # know why. Missing state is created on first run above; corrupt state
        # is an explicit recovery event.
        raise SignerKeyError(
            "The existing RAMIFY signing key is corrupt or unreadable. "
            "Back up the local ledger, then explicitly reset/rekey the demo signer."
        ) from exc


def load_issuer_private_key(issuer_ref: str) -> Ed25519PrivateKey:
    """Seed-step only. Issuer private keys are not available at runtime."""
    seed_file = SEED_PRIVATE_DIR / "keys.json"
    if not seed_file.exists():
        raise FileNotFoundError("no seed material; run `make seed` first")
    keypairs = json.loads(seed_file.read_text(encoding="utf-8"))
    return Ed25519PrivateKey.from_private_bytes(
        bytes.fromhex(keypairs[issuer_ref]["private_hex"])
    )


def public_keys() -> dict[str, str]:
    try:
        from ramify.crypto.embedded_pubkeys import PUBLIC_KEYS
    except ImportError as exc:  # pragma: no cover - exercised by a fresh clone
        raise RuntimeError(
            "embedded public keys are missing; run `make seed`"
        ) from exc
    merged = dict(PUBLIC_KEYS)

    # Migration/repair path: if a legacy machine-local private signer exists,
    # derive its public half directly. This prevents an upgraded demo from
    # verifying a receipt against the unrelated signer key embedded in the new
    # package. It also repairs a missing/stale signer_public_key.json file.
    private_target = local_data_store() / "signer_key.json"
    if private_target.exists():
        try:
            payload = read_json(private_target, dict)
            raw = payload.get(RAMIFY_SIGNER)
            if isinstance(raw, str):
                private = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(raw))
                value = _to_raw_public(private.public_key()).hex()
                merged[RAMIFY_SIGNER] = value
                _sync_runtime_signer_public(private)
                return merged
        except (StoreCorrupt, TypeError, ValueError):
            # Corrupt private state is handled by load_signer_private_key() when
            # signing is next attempted. Do not trust a stale public companion.
            pass

    runtime_public = local_data_store() / "signer_public_key.json"
    if runtime_public.exists():
        try:
            payload = read_json(runtime_public, dict)
            value = payload.get(RAMIFY_SIGNER)
            if isinstance(value, str) and len(value) == 64:
                merged[RAMIFY_SIGNER] = value
        except StoreCorrupt:
            pass
    return merged


def load_public_key(ref: str) -> Ed25519PublicKey | None:
    raw = public_keys().get(ref)
    if raw is None:
        return None
    return Ed25519PublicKey.from_public_bytes(bytes.fromhex(raw))
